version: '3.4'

services:
  store-api:
    image: psa_storeapi:latest
    build:
      context: .
      dockerfile: Services/Store/Store.API/Dockerfile

  customer-api:
    image: psa_customerapi:latest
    build:
      context: .
      dockerfile: Services/Customer/Customer.API/Dockerfile

  identity-api:
    image: psa_identityapi:latest
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
