version: '3.4'

services:
  store-api:
    image: psa_storeapi:latest
    build:
      context: .
      dockerfile: Services/Store/Store.API/Dockerfile

  customer-api:
    image: psa_customerapi:latest
    build:
      context: .
      dockerfile: Services/Customer/Customer.API/Dockerfile

  identity-api:
    image: psa_identityapi:latest
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  ocelot-api-gw:
    image: psa_ocelotapigw:latest
    build:
      context: .
      dockerfile: ApiGateway/OcelotApiGw/Dockerfile

  aspmvc-web:
    image: psa_aspmvcweb:latest
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile