apiVersion: v1
kind: Service
metadata:
  name: aspmvc-web
  labels:
    app: my-physical-store
    env: dev
    component: aspmvc-web
spec:
  ports:
  - port: 443
  selector:
    app: my-physical-store
    env: dev
    component: aspmvc-web-deploy
