apiVersion: v1
kind: Service
metadata:
  name: customer-api
  labels:
    app: my-physical-store
    env: dev
    component: customer-api
spec:
  ports:
  - port: 5001
  selector:
    app: my-physical-store
    env: dev
    component: customer-api-deploy
