apiVersion: v1
kind: Service
metadata:
  name: identity-api
  labels:
    app: my-physical-store
    env: dev
    component: identity-api
spec:
  ports:
  - port: 443
  selector:
    app: my-physical-store
    env: dev
    component: identity-api-deploy
