apiVersion: v1
kind: Service
metadata:
  name: ocelot-api-gw
  labels:
    app: my-physical-store
    env: dev
    component: ocelot-api-gw
spec:
  ports:
  - port: 443
  selector:
    app: my-physical-store
    env: dev
    component: ocelot-api-gw-deploy
