apiVersion: v1
kind: Service
metadata:
  name: spa-web
  labels:
    app: my-physical-store
    env: test
    component: spa-web
spec:
  ports:
  - port: 80
  selector:
    app: my-physical-store
    env: test
    component: spa-web-deploy
