apiVersion: v1
kind: Service
metadata:
  name: store-api
  labels:
    app: my-physical-store
    env: dev
    component: store-api
spec:
  ports:
  - port: 443
  selector:
    app: my-physical-store
    env: dev
    component: store-api-deploy
