apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aspmvc-web-deploy
spec:
  paused: true
  template:
    metadata:
      labels:
        app: my-physical-store
        env: dev
        component: aspmvc-web-deploy
    spec:
      containers:
      - name: aspmvc-web-deploy
        image: xjeunot59/psa_aspmvcweb
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
           configMapKeyRef:
             name: psa-dev-config-files
             key: AspmvcWeb__ASPNETCORE_ENVIRONMENT
        - name: ClusterMode
          valueFrom:
           configMapKeyRef:
             name: psa-dev-config-files
             key: AspmvcWeb__ClusterMode
        - name: K8s__SecretFile
          valueFrom:
           configMapKeyRef:
             name: psa-dev-config-files
             key: AspmvcWeb__K8s__SecretFile
        - name: Azure__EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: psa-dev-config-files
             key: AspmvcWeb__Azure__EventBusConnection
        - name: Azure__EventBusEntityPath
          valueFrom:
           configMapKeyRef:
             name: psa-dev-config-files
             key: AspmvcWeb__Azure__EventBusEntityPath
        - name: Azure__SubscriptionClientName
          valueFrom:
           configMapKeyRef:
             name: psa-dev-config-files
             key: AspmvcWeb__Azure__SubscriptionClientName
        - name: Azure__KeyVaultName
          valueFrom:
           configMapKeyRef:
             name: psa-dev-config-files
             key: AspmvcWeb__Azure__KeyVaultName
        - name: Azure__AzureADApplicationId
          valueFrom:
           configMapKeyRef:
             name: psa-dev-config-files
             key: AspmvcWeb__Azure__AzureADApplicationId
        - name: Azure__AzureADPassword
          valueFrom:
           configMapKeyRef:
             name: psa-dev-config-files
             key: AspmvcWeb__Azure__AzureADPassword
        - name: Cluster__CertificateSecretName
          valueFrom:
           configMapKeyRef:
             name: psa-dev-config-files
             key: AspmvcWeb__Cluster__CertificateSecretName
        - name: Cluster__CertificateSecretPassword
          valueFrom:
           configMapKeyRef:
             name: psa-dev-config-files
             key: AspmvcWeb__Cluster__CertificateSecretPassword
        - name: KestrelNoClusterHttpsCertFile__Path
          valueFrom:
           configMapKeyRef:
             name: psa-dev-config-files
             key: AspmvcWeb__KestrelNoClusterHttpsCertFile__Path
        - name: KestrelNoClusterHttpsCertFile__Password
          valueFrom:
           configMapKeyRef:
             name: psa-dev-config-files
             key: AspmvcWeb__KestrelNoClusterHttpsCertFile__Password
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secret-aspmvc-web
