apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: identity-api-deploy
spec:
  paused: true
  template:
    metadata:
      labels:
        app: my-physical-store
        env: test
        component: identity-api-deploy
    spec:
      containers:
      - name: identity-api-deploy
        image: xjeunot59/psa_identityapi
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__ASPNETCORE_ENVIRONMENT
        - name: ClusterMode
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__ClusterMode
        - name: K8s__SecretFile
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__K8s__SecretFile
        - name: Azure__EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__Azure__EventBusConnection
        - name: Azure__EventBusEntityPath
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__Azure__EventBusEntityPath
        - name: Azure__SubscriptionClientName
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__Azure__SubscriptionClientName
        - name: Azure__KeyVaultName
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__Azure__KeyVaultName
        - name: Azure__AzureADApplicationId
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__Azure__AzureADApplicationId
        - name: Azure__AzureADPassword
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__Azure__AzureADPassword
        - name: Cluster__CertificateSecretName
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__Cluster__CertificateSecretName
        - name: Cluster__CertificateSecretPassword
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__Cluster__CertificateSecretPassword
        - name: KestrelNoClusterHttpsCertFile__Path
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__KestrelNoClusterHttpsCertFile__Path
        - name: KestrelNoClusterHttpsCertFile__Password
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__KestrelNoClusterHttpsCertFile__Password
        - name: MongoDbConfig__ConnectionString
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__MongoDbConfig__ConnectionString
        - name: MongoDbConfig__Datebase
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__MongoDbConfig__Datebase
        - name: MongoDbConfig__User
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__MongoDbConfig__User
        - name: MongoDbConfig__Password
          valueFrom:
           configMapKeyRef:
             name: psa-test-config-files
             key: IdentityApi__MongoDbConfig__Password
        ports:
        - containerPort: 80
      volumes:
      - name: secrets
        secret:
          secretName: secret-identity-api
